//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorkersRightsComputer.rc
//
#define IDOK2                           3
#define IDOK3                           4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WORKERSRIGHTSCOMPUTER_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DIALOG_WORK_PERIOD          131
#define IDD_DIALOG_EMPLOYER             133
#define IDD_DIALOG_VACATIONS            135
#define IDD_DIALOG_FAMILY_PART          137
#define IDD_DIALOG1                     139
#define IDD_DIALOG_ASK                  139
#define IDD_DIALOG_WAGE_PERIODS         141
#define IDC_WORK_PERIOD                 1000
#define IDC_DATETIMEPICKER_START        1001
#define IDC_EMPLOYER                    1001
#define IDC_DATETIMEPICKER_END          1002
#define IDC_COMMENTS                    1002
#define IDC_DATETIMEPICKER_START2       1002
#define IDC_DATETIMEPICKER_NOTICE       1003
#define IDC_EDIT_PERIODS                1004
#define IDC_CHECK_SUNDAY                1005
#define IDC_CHECK_MONDAY                1006
#define IDC_CHECK_TUESDAY               1007
#define IDC_CHECK_WEDNESDAY             1008
#define IDC_CHECK_THURSDAY              1009
#define IDC_CHECK_FRIDAY                1010
#define IDC_CHECK_SATURDAY              1011
#define IDC_DATETIMEPICKER_NOTICE2      1012
#define IDC_CHECK_SATURDAY2             1012
#define IDC_CHECK_NO_NOTICE             1012
#define IDC_EDIT_MONTH_SALARY           1014
#define IDC_RADIO_MIN_WAGE              1015
#define IDC_RADIO_MONTHLY               1016
#define IDC_RADIO_HOURLY                1017
#define IDC_EDIT_HOUR_SALARY            1018
#define IDC_EDIT_HOURS_PER_WEEK         1019
#define IDC_STATIC_PERIOD               1020
#define IDC_BUTTON_SAVE                 1021
#define IDC_BUTTON_LOAD                 1022
#define IDC_BUTTON_RESET                1023
#define IDC_EDIT_FIRST_NAME             1024
#define IDC_EDIT_FAMILY_NAME            1025
#define IDC_EDIT_ID                     1026
#define IDC_EDIT_TEL                    1027
#define IDC_COMBO_HOLIDAYS              1028
#define IDC_EDIT_HOLIDAYS_LASTY_WORK    1029
#define IDC_EDIT_HOLIDAYS_LASTY_PAID    1030
#define IDC_EDIT_HOLIDAYS_LASTY_FROM    1031
#define IDC_STATIC_LAST_YEAR            1032
#define IDC_EDIT_HOLIDAYS_PREVY_WORK    1033
#define IDC_EDIT_HOLIDAYS_PREVY_PAID    1034
#define IDC_EDIT_HOLIDAYS_PREVY_FROM    1035
#define IDC_STATIC_PREV_YEAR            1036
#define IDC_CHECK_SEVERANCE_LESS_THAN_YEAR 1037
#define IDC_CHECK_VACATION_YEARS        1038
#define IDC_EDIT_VACATION_YEARS         1039
#define IDC_CHECK_RECUPERATION_YEARS    1040
#define IDC_EDIT_RECUPERATION_YEARS     1041
#define IDC_CHECK_ONLY_SEVERANCE        1042
#define IDC_CHECK_ACTIVE_PENSION        1043
#define IDC_EDIT_ADDITIONAL_SUM         1044
#define IDC_EDIT_EMP_EMAIL              1045
#define IDC_EDIT_ADDITIONAL_SUM2        1045
#define IDC_EDIT_PAID_SUM               1045
#define IDC_EDIT_EMP_EMAIL2             1046
#define IDC_EDIT_HOLIDAYS_PREVY_N_YEARS 1047
#define IDC_RADIO_ID                    1048
#define IDC_RADIO_PASSPORT              1049
#define IDC_EDIT_EMAIL                  1050
#define IDC_EDIT_EMP_NAME               1051
#define IDC_EDIT_ADDRESS                1052
#define IDC_EDIT_EMP_TEL                1055
#define IDC_EDIT_EMP_ID                 1056
#define IDC_EDIT_EMP_ADDRESS            1057
#define IDC_EDIT_EMP_ROLE               1062
#define IDC_EDIT_ADDITIONAL_DESC        1063
#define IDC_EDIT_EMP_COMMENT            1063
#define IDC_EDIT_SUMMARY                1064
#define IDC_RADIO_PRIVATE               1065
#define IDC_EDIT_ADDITIONAL_DESC2       1065
#define IDC_EDIT_PAID_DESC              1065
#define IDC_RADIO_COMPANY               1066
#define IDC_RADIO_OSEK                  1067
#define IDC_EDIT4                       1068
#define IDC_EDIT6                       1069
#define IDC_EDIT_FILLED_BY              1071
#define IDC_DATETIMEPICKER_VAC_START    1072
#define IDC_DATETIMEPICKER_VAC_END      1073
#define IDC_BUTTON_VAC_ADD              1074
#define IDC_BUTTON_VAC_CLEAR            1075
#define IDC_EDIT_VAC_LIST               1076
#define IDC_BUTTON_VAC_CLEAR_LAST       1077
#define IDC_CHECK_14DAYS_VAC4SEVRANCE   1078
#define IDC_BUTTON_FAMILY_PART          1079
#define IDC_CHECK_FAMILY_PART           1080
#define IDC_DATETIMEPICKER1             1081
#define IDC_EDIT_HOURS_BY_COMPANY       1082
#define IDC_BUTTON_ADD_PERIOD           1083
#define IDC_EDIT_FAMILY_PART_STATUS     1084
#define IDC_BUTTON_FAMILY_PART_CLEAR    1085
#define IDC_STATIC_ASK                  1086
#define IDC_EDIT_PERCENT_BY_COMPANY     1086
#define IDC_BUTTON_FAMILY_PART_CLEAR2   1087
#define IDC_BUTTON_ADD_EMPLOYER         1088
#define IDC_BUTTON_ADD_PERIOD_PERCENT   1088
#define IDC_BUTTON_ADD_CONTACT          1089
#define IDC_BUTTON_FAMILY_PART_CLEAR3   1089
#define IDC_BUTTON_FAMILY_PART_CLEAR_LAST 1089
#define IDC_BUTTON_CLEAR_CONTACTS       1090
#define IDC_BUTTON_CLEAR_CONTACT        1091
#define IDC_EDIT_CONTACTS               1092
#define IDC_BUTTON_CLEAR_CONTACT2       1093
#define IDC_BUTTON_EDIT_CONTACT         1093
#define IDC_EDIT1                       1093
#define IDC_EDIT_PAY_PER_HOLY_DAY       1093
#define IDC_CHECK_PAID_VACATION         1094
#define IDC_CHECK2                      1095
#define IDC_CHECK_PAID_RECUP            1095
#define IDC_RADIO_DIFF_WAGES            1096
#define IDC_BUTTON1                     1097
#define IDC_BUTTON_EDIT_WAGE            1097
#define IDC_BUTTON_ADD_WAGE_PERIOD      1097
#define ID_FILE_EXIT                    32771
#define ID_COMPUTE_ALL                  32772
#define ID_FILE_LOAD                    32773
#define ID_FILE_SAVEAS                  32774
#define ID_TEST_CREATEDIR               32775
#define ID_FILE_LOADOLDCASE             32776
#define ID_TEST_VERIFYBATCH             32777
#define ID_TEST_READHEBREW              32778
#define ID_TEST_WRITEHTML               32779
#define ID_TEST_LOADXML                 32780
#define ID_TEST_LOADTXT                 32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
